name = "Digital Movement Indonesia"
license = "MIT"
licenselink = "https://github.com/uicardiodev/hugo-lime/blob/master/LICENSE.md"
description = ""
homepage = "http://digitalmovement.id/"
tags = ["minimal","blog","services","responsive","bootstrap","dimo","dmi","digitalmovementindonesia","illustrations"]
features = ["cover","pricing","faq","parteners","blog","work","portfolio","contact","illustrations"]
min_version = "0.47.1"

[author]
  name = "dimo-theme-v2"
  homepage = "https://digitalmovement.id/"

[developer]
	name = "Andria Putro"
	homepage = "https://github.com/putroandrianto"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""